# Generated by Django 6.0.1 on 2026-01-09 12:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("competitions", "0003_matchteam_team_alter_matchteam_unique_together"),
        ("players", "0001_initial"),
        ("teams", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("pass", "Pass"),
                            ("shot", "Shot"),
                            ("turnover", "Turnover"),
                            ("recovery", "Recovery"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "timestamp_ms",
                    models.PositiveIntegerField(
                        help_text="Milliseconds from match start"
                    ),
                ),
                (
                    "period",
                    models.PositiveSmallIntegerField(
                        help_text="Match period (1=1st half, 2=2nd half, etc.)"
                    ),
                ),
                (
                    "x",
                    models.FloatField(
                        blank=True, help_text="X coordinate on pitch (0-100)", null=True
                    ),
                ),
                (
                    "y",
                    models.FloatField(
                        blank=True, help_text="Y coordinate on pitch (0-100)", null=True
                    ),
                ),
                (
                    "confidence",
                    models.FloatField(
                        blank=True,
                        help_text="Event confidence score (0.0–1.0)",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="competitions.match",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="events",
                        to="players.player",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="events",
                        to="teams.team",
                    ),
                ),
            ],
            options={
                "db_table": "events",
                "ordering": ["timestamp_ms"],
                "indexes": [
                    models.Index(
                        fields=["match", "event_type"], name="events_match_i_a7f0e3_idx"
                    ),
                    models.Index(fields=["player"], name="events_player__054ada_idx"),
                ],
            },
        ),
    ]
