# Generated by Django 6.0.1 on 2026-01-09 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
        ("players", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="outcome",
            field=models.CharField(
                choices=[
                    ("success", "Success"),
                    ("fail", "Fail"),
                    ("unknown", "Unknown"),
                ],
                default="unknown",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="related_event",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="derived_events",
                to="events.event",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="secondary_player",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="secondary_events",
                to="players.player",
            ),
        ),
    ]
