# Generated by Django 6.0.1 on 2026-01-09 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("competitions", "0002_matchteam"),
        ("teams", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="matchteam",
            name="team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="matches",
                to="teams.team",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="matchteam",
            unique_together={("match", "team")},
        ),
    ]
