# Generated by Django 6.0.1 on 2026-04-01 10:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('competitions', '0003_matchteam_team_alter_matchteam_unique_together'),
        ('events', '0002_event_outcome_event_related_event_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoUpload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=255)),
                ('file_path', models.CharField(max_length=500)),
                ('file_size', models.BigIntegerField(help_text='File size in bytes')),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
                ('width', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('fps', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('uploading', 'Uploading'), ('uploaded', 'Uploaded'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='uploading', max_length=20)),
                ('period', models.PositiveSmallIntegerField(blank=True, help_text='Match period (1=1st half, 2=2nd half)', null=True)),
                ('video_start_offset_ms', models.PositiveIntegerField(default=0, help_text='Video start offset in milliseconds from match start')),
                ('events_count', models.IntegerField(default=0)),
                ('processing_error', models.TextField(blank=True, null=True)),
                ('json_output_path', models.CharField(blank=True, help_text='Path to JSON file with detected events', max_length=500, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('match', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='video_uploads', to='competitions.match')),
            ],
            options={
                'db_table': 'video_uploads',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='VideoClip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('clip_type', models.CharField(choices=[('goal', 'Goal'), ('shot', 'Shot'), ('dangerous_moment', 'Dangerous Moment'), ('pass', 'Key Pass'), ('tackle', 'Tackle'), ('save', 'Save'), ('other', 'Other')], max_length=20)),
                ('title', models.CharField(help_text='Human-readable title for the clip', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Description of what happens in the clip', null=True)),
                ('file_path', models.CharField(help_text='Path to clipped video file', max_length=500)),
                ('file_size', models.BigIntegerField(blank=True, help_text='File size in bytes', null=True)),
                ('duration_seconds', models.FloatField(help_text='Duration of the clip in seconds')),
                ('start_time_seconds', models.FloatField(help_text='Start time in original video (seconds)')),
                ('end_time_seconds', models.FloatField(help_text='End time in original video (seconds)')),
                ('timestamp_ms', models.PositiveIntegerField(help_text='Event timestamp in milliseconds from match start')),
                ('confidence', models.FloatField(blank=True, help_text='Confidence score for clip importance (0.0-1.0)', null=True)),
                ('thumbnail_path', models.CharField(blank=True, help_text='Path to thumbnail image', max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(blank=True, help_text='Related event that triggered this clip', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='video_clips', to='events.event')),
                ('video_upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clips', to='analytics.videoupload')),
            ],
            options={
                'db_table': 'video_clips',
                'ordering': ['timestamp_ms'],
                'indexes': [models.Index(fields=['video_upload', 'clip_type'], name='video_clips_video_u_7b828d_idx'), models.Index(fields=['timestamp_ms'], name='video_clips_timesta_5f3e3e_idx')],
            },
        ),
    ]
